### ISSUE TITLE
J4de - `USSD.sol#initialize` mint without deposit collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#177]
J4de

medium

# `USSD.sol#initialize` mint without deposit collateral

## Summary

`USSD.sol#initialize` mint 10000 USSD without deposit any collateral

## Vulnerability Detail

The described in the whitepaper:

> USSD coin is ’initialized’ with one-time minting of 1000 USSD, taking 1000
> DAI as collateral.

But in the implementation, the `initialize` function does not deposit any DAI. And mint 10000 USSD instead of the 1000 USSD mentioned in the whitepaper.

## Impact

Does not meet the white paper description, and may cause the initial state of USSD to be unstable (lack of sufficient collateral to resist depeg)

## Code Snippet

https://github.com/USSDofficial/ussd-contracts/blob/f44c726371f3152634bcf0a3e630802e39dec49c/contracts/USSD.sol#L42

## Tool used

Manual Review

## Recommendation

It is recommended to mint 1000 USSD with 1000 DAI

**Comment by Nabeel-javaid** [comment]
> Escalate for 10USDC I this counts as admin input error, and is therefore invalid. The admin can/should transfer the initial DAI Collateral as part of the deployment

In the whitepaper, it states that there will be an initial USSD mint of 1000 tokens for supplying initial liquidity. These tokens are supposed to be backed by collateral of 1000 DAI.

In the initialize function, 10,000 tokens (rather than the stated 1000) are minted, and there is no corresponding deposit of DAI collateral at all. These tokens are totally unbacked.

**Comment by Shogoki** [comment]
> > Escalate for 10USDC I this counts as admin input error, and is therefore invalid. The admin can/should transfer the initial DAI Collateral as part of the deployment
> 
> In the whitepaper, it states that there will be an initial USSD mint of 1000 tokens for supplying initial liquidity. These tokens are supposed to be backed by collateral of 1000 DAI.
> 
> In the initialize function, 10,000 tokens (rather than the stated 1000) are minted, and there is no corresponding deposit of DAI collateral at all. These tokens are totally unbacked.

I agree that this is far from good, but they are only unbacked, if the admin/deployer does not send the collateral to the contract, which could be part of the deployment process. 
Thats why i think this counts as admin input, which is not valid according to sherlock rules.

**Comment by ctf-sec** [comment]
The impact is not severe enough to be considered medium, low

**Comment by Nabeel-javaid** [comment]
> The impact is not severe enough to be considered medium, low

These tokens could be unbacked if there isn't any Dai as collateral. Which will cause alot of issues.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
Although the issue is valid the impact of the issue can be considered as low based on the escalation.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Shogoki](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/177/#issuecomment-1604625851): accepted
