### ISSUE TITLE
J4de - `USSD.sol#UniV3SwapInput` does not consider that `_sellAmount` may be `0` and sell all collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#182]
J4de

high

# `USSD.sol#UniV3SwapInput` does not consider that `_sellAmount` may be `0` and sell all collateral

## Summary

When uniswap V3 `amountIn` param of `exactInput` function is `0`, the `exactInput` function will sell all the token. Resulting in the possibility of an unexpected full sale of the collateral.

## Vulnerability Detail

**1. The vulnerability**

The [`exactInput`](https://github.com/Uniswap/swap-router-contracts/blob/main/contracts/interfaces/IV3SwapRouter.sol#L35) function will sell all tokens when `amountIn` is `0`.

```solidity
File: USSD.sol
242     function approveToRouter(address _token) public {
243         IERC20Upgradeable(_token).approve(
244             address(uniRouter),
245             0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
246         );
247     }
```

And the `approveToRouter` function will approve `uint256.max` to uniswap. So if the `_sellAmount` param of `UniV3SwapInput` is `0`, the all collateral of USSD will be sell.

**2. How to make `_sellAmount` to `0`**

```solidity
File: USSDRebalancer.sol
117         if (collateralval > amountToBuyLeftUSD) {
118           // sell a portion of collateral and exit
119           if (collateral[i].pathsell.length > 0) {
120             uint256 amountBefore = IERC20Upgradeable(baseAsset).balanceOf(USSD);
121 >>          uint256 amountToSellUnits = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * ((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18) / 1e18;
122             IUSSD(USSD).UniV3SwapInput(collateral[i].pathsell, amountToSellUnits);
123             amountToBuyLeftUSD -= (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
124             DAItosell += (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
125           } else {
```

If the `collateralval` is large and the `amountToBuyLeftUSD` is small, the result of `((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18)` is `0`. Then the `amountToSellUnits` is `0` and call `UniV3SwapInput` function.

## Impact

A certain collateral may be sold in full, resulting in depeg of USSD prices.

## Code Snippet

https://github.com/USSDofficial/ussd-contracts/blob/f44c726371f3152634bcf0a3e630802e39dec49c/contracts/USSD.sol#L229

## Tool used

Manual Review

## Recommendation

It is recommended to check `_sellAmount` is not `0`

```diff
    function UniV3SwapInput(
        bytes memory _path,
        uint256 _sellAmount
    ) public override onlyBalancer {
+       require(_sellAmount != 0);
        IV3SwapRouter.ExactInputParams memory params = IV3SwapRouter
            .ExactInputParams({
                path: _path,
                recipient: address(this),
                //deadline: block.timestamp,
                amountIn: _sellAmount,
                amountOutMinimum: 0
            });
        uniRouter.exactInput(params);
    }
```

**Comment by yttriumzz** [comment]
Escalate for 10 USDC
I think this is not a duplicate of #111

**Comment by ctf-sec** [comment]
I agreee this is not a duplicate of #111 aand after a second look,

I think this is not a valid issue

```solidity
 IV3SwapRouter.ExactInputParams memory params = IV3SwapRouter
            .ExactInputParams({
                path: _path,
                recipient: address(this),
                //deadline: block.timestamp,
                amountIn: _sellAmount,
                amountOutMinimum: 0
            });
        uniRouter.exactInput(params);
```

if _sellAmount is 0, the exactInput will revert anyway

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique 
As pointed by the Lead judge, if _sellAmount was 0 then the swap would revert

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yttriumzz](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/182/#issuecomment-1604496508): accepted
