### ISSUE TITLE
J4de - `StableOracleDAI.sol#getPriceUSD` price calculation error

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#186]
J4de

high

# `StableOracleDAI.sol#getPriceUSD` price calculation error

## Summary

`StableOracleDAI.sol#getPriceUSD` price calculation error causing get wrong price

## Vulnerability Detail

```solidity
File: oracles/StableOracleDAI.sol
 33     function getPriceUSD() external view override returns (uint256) {
--skip--
 50         return
 51             (wethPriceUSD * 1e18) /
 52             ((DAIWethPrice + uint256(price) * 1e10) / 2);
 53     }
```

The `getPriceUSD` function will return DAI/USD price.

- `wethPriceUSD` is WETH/USD price
- `DAIWethPrice` is DAI/WETH price
- `price` is WETH/USD price

So the correct calculation method should be: DAIWethPrice / ((wethPriceUSD + price * 1e10) / 2)

## Impact

The price of DAI/USD is wrong, which may cause instability of USSD

## Code Snippet

https://github.com/USSDofficial/ussd-contracts/blob/f44c726371f3152634bcf0a3e630802e39dec49c/contracts/oracles/StableOracleDAI.sol#L50-L52

## Tool used

Manual Review

## Recommendation

```diff
        return
-           (wethPriceUSD * 1e18) /
-           ((DAIWethPrice + uint256(price) * 1e10) / 2);
+           (DAIWethPrice * 1e18) /
+           ((wethPriceUSD + uint256(price) * 1e10) / 2);
```

Duplicate of #102

**Comment by yttriumzz** [comment]
Escalate for 10 USDC
I think this is not a duplicate of #236

**Comment by ctf-sec** [comment]
This is the duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/102

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yttriumzz](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/186/#issuecomment-1604495150): accepted
