### ISSUE TITLE
J4de - `USSDRebalancer.sol#BuyUSSSellCollateral` assumes that DAI will always be the first collateral

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#190]
J4de

medium

# `USSDRebalancer.sol#BuyUSSSellCollateral` assumes that DAI will always be the first collateral

## Summary

If the price of USSD drops, collateral will be sold in order to buy USSD. And the  `BuyUSSSellCollateral` function assumes that DAI will always be the first collateral.

## Vulnerability Detail

```solidity
File: USSDRebalancer.sol
115       for (uint256 i = 0; i < collateral.length; i++) {
116         uint256 collateralval = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * 1e18 / (10**IERC20MetadataUpgradeable(collateral[i].token).decimals()) * collateral[i].oracle.getPriceUSD() / 1e1    8;
117         if (collateralval > amountToBuyLeftUSD) {
118           // sell a portion of collateral and exit
119           if (collateral[i].pathsell.length > 0) {
120             uint256 amountBefore = IERC20Upgradeable(baseAsset).balanceOf(USSD);
121             uint256 amountToSellUnits = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * ((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18) / 1e18;
122             IUSSD(USSD).UniV3SwapInput(collateral[i].pathsell, amountToSellUnits);
123             amountToBuyLeftUSD -= (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
124             DAItosell += (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
125           } else {
126             // no need to swap DAI
127 >>          DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
128           }
```

Line 127 uses the `=` instead of `+=`, this works fine when DAI is the first collateral. But if DAI is no longer the first collateral (admin can change the order of collateral), this will be problematic. If DAI is not the first collateral, line 127 will use the amount of DAI to cover all previous accumulated collateral amounts.

## Impact

If DAI is not the first collateral and first collater is not enough, balancer will sell less collateral than expected. And will cause USSD rebalancer to become unstable.

## Code Snippet

https://github.com/USSDofficial/ussd-contracts/blob/f44c726371f3152634bcf0a3e630802e39dec49c/contracts/USSDRebalancer.sol#L127

## Tool used

Manual Review

## Recommendation

```diff
          } else {
            // no need to swap DAI
-           DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
+           DAItosell += IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
          }
```

**Comment by yttriumzz** [comment]
Escalate for 10 USDC
I think this is not a duplicate of #111

**Comment by ctf-sec** [comment]
Agree this is not a duplicate of #111 

I think this issue can be separate low 

because "whether DAI will always be the first collateral" depends on admin configuration

**Comment by hrishibhat** [comment]
Result:
Low
Unique
DAI being the first collateral is admin responsibility as its importance is clearly mentioned across the code and implementation

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yttriumzz](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/190/#issuecomment-1604497097): accepted
