### ISSUE TITLE
T1MOH - StableOracle contracts will return the wrong price for asset if underlying aggregator hits minAnswer

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#197]
T1MOH

medium

# StableOracle contracts will return the wrong price for asset if underlying aggregator hits minAnswer

## Summary
Chainlink aggregators have a built in circuit breaker if the price of an asset goes outside of a predetermined price band. The result is that if an asset experiences a huge drop in value (i.e. LUNA crash) the price of the oracle will continue to return the minPrice instead of the actual price of the asset. This would allow user to continue borrowing with the asset but at the wrong price. This is exactly what happened to [Venus on BSC when LUNA imploded](https://rekt.news/venus-blizz-rekt/).

## Vulnerability Detail
ChainlinkAggregators have minPrice and maxPrice circuit breakers built into them. This means that if the price of the asset drops below the minPrice, the protocol will continue to value the token at minPrice instead of it's actual value. This will allow users to take out huge amounts of bad debt and bankrupt the protocol.

Example:
TokenA has a minPrice of $1. The price of TokenA drops to $0.10. The aggregator still returns $1 allowing the user to borrow against TokenA as if it is $1 which is 10x it's actual value.

## Impact
In the event that an asset crashes (i.e. LUNA) the protocol can be manipulated to give out loans at an inflated price

## Code Snippet
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L48
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleWBTC.sol#L21-L26
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleWETH.sol#L21-L26

## Tool used

Manual Review

## Recommendation
StableOracle contracts should check the returned answer against the minPrice/maxPrice and revert if the answer is outside of the bounds:
```solidity
(, int256 price, , , ) = priceFeed.latestRoundData(); 

if (price >= maxPrice || answer <= minPrice) revert();
```

Duplicate of #598

**Comment by T1MOH593** [comment]
Escalate for 10 USDC

This is not a duplicate of #31 as talks about price hitting minAnswer, but not stale price.

This escalation fully describes why issue is different from stale price
https://github.com/sherlock-audit/2023-02-blueberry-judging/issues/18#issuecomment-1475379093

**Comment by ctf-sec** [comment]
Based on https://github.com/sherlock-audit/2023-02-blueberry-judging/issues/18#issuecomment-1475379093

I think all chainlink finding that talks about the minAnswer issue should be grouped to create a separate valid medium issue

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #598

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [T1MOH593](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/197/#issuecomment-1604567374): accepted
