### ISSUE TITLE
Bauer - Inconsistency between price feeds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#201]
Bauer

high

# Inconsistency between price feeds

## Summary
The getPriceUSD() function retrieves price data from two different sources, DAIEthOracle.quoteSpecificPoolsWithTimePeriod() and priceFeedDAIETH.latestRoundData(). However, these sources provide prices for different pairs, WETH/DAI and DAI/ETH, respectively. This inconsistency can lead to inaccurate calculations when determining the USD price. It is important to ensure the use of consistent price data from the same pair or adjust the calculations accordingly to obtain accurate pricing information.( There is no direct source of price data available for the ETH/DAI trading pair in chainlink)

## Vulnerability Detail
The `StableOracleDAI.getPriceUSD()` function retrieves price data from two different sources: `DAIEthOracle.quoteSpecificPoolsWithTimePeriod()` and `priceFeedDAIETH.latestRoundData()`. However, it is important to note that these two price sources provide prices in an inconsistent manner. Here's a breakdown of the inconsistency:

DAIEthOracle.quoteSpecificPoolsWithTimePeriod(): This function returns the price of the WETH/DAI pair. It calculates the price by considering the specified pools, the base token (WETH), and the quote token (DAI). The returned price represents how much DAI is needed to purchase one unit of WETH.
https://etherscan.io/address/0xb210ce856631eeeb767efa666ec7c1c57738d438/advanced#readContract
```solidity
    uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            pools, // DAI/WETH pool uni v3
            600 // period
        );
```

priceFeedDAIETH.latestRoundData(): This source provides the price of the DAI/ETH pair. It gives the price of how much ETH is needed to purchase one unit of DAI.
https://docs.chain.link/data-feeds/price-feeds/addresses/?network=ethereum
```solidity
(, int256 price, , , ) = priceFeedDAIETH.latestRoundData();

```

The inconsistency arises because the `getPriceUSD()` function combines these two prices to calculate the final USD price. It multiplies the USD price of WETH (wethPriceUSD) by 10^18 and divides it by the sum of DAIWethPrice (WETH/DAI price) and the price value (DAI/ETH price) multiplied by 10^8, divided by 2.

Due to the mismatched price sources, the resulting USD price may not accurately reflect the true market value. It is crucial to use consistent price data from the same pair or adjust the calculations accordingly to ensure accurate pricing calculations.
## Impact
Due to the absence of a direct ETH/DAI price feed and the use of alternative calculations, there is a possibility that the computed price may be higher than the actual market price. 
## Code Snippet
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L48
## Tool used

Manual Review

## Recommendation
Calculating accurate WETH/DAI Price based on price data from Chainlink

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Not a duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/909
This is a low issue as calculating the price of Dai from multiple sources and not using a unique price price feed can be considered a protocol choice.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [T1MOH593](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/201/#issuecomment-1604534641): accepted
