### ISSUE TITLE
nobody2018 - StableOracleDAI.getPriceUSD incorrectly uses the price returned by priceFeedDAIETH.latestRoundData()

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#243]
nobody2018

high

# StableOracleDAI.getPriceUSD incorrectly uses the price returned by priceFeedDAIETH.latestRoundData()

## Summary

`StableOracleDAI.getPriceUSD` incorrectly uses the price returned by `priceFeedDAIETH.latestRoundData()`.

## Vulnerability Detail

Three different oracles are used in the `StableOracleDAI.getPriceUSD` function to obtain prices:

1.  `DAIEthOracle.quoteSpecificPoolsWithTimePeriod` gets **DAI per ether**, this value is based on e18. Suppose the obtained price is A=1814e18.
2.  `ethOracle.getPriceUSD` gets **USD per ether**, this value is based on e18. Suppose the obtained price is B=1815e18.
3.  `priceFeedDAIETH.latestRoundData` gets **ether per DAI**, which is based on e18, not the e8 mentioned in the [[comment](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L46)](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L46). [[0x773616E4d11A78F511299002da57A0a94577F1f4](https://etherscan.io/address/0x773616E4d11A78F511299002da57A0a94577F1f4#readContract)](https://etherscan.io/address/0x773616E4d11A78F511299002da57A0a94577F1f4#readContract) is the Chainlink DAI/ETH feed. Suppose the obtained price is C=[[551720649183640](https://etherscan.io/unitconverter?wei=551720649183640)](https://etherscan.io/unitconverter?wei=551720649183640), this value is 0.00055172064918364.

According to the [[formula](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L51-L52)](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L51-L52), price = (wethPriceUSD * 1e18) / ((DAIWethPrice + uint256(price) * 1e10) / 2) = (B * 1e18) / ((A + C * 1e10) / 2) = (1815e18 * 1e18) / ((1814e18 + 551720e18) / 2) = 1815e18 * 1e18 / 276767e18 = 0.0065578e18. This value is the usd price of a DAI. **This means that 1 USD can buy 152.49 DAI**.

## Impact

The gap between StableOracleDAI.getPriceUSD and the actual price is very large.

## Tool used

Manual Review

## Recommendation

```diff
--- a/ussd-contracts/contracts/oracles/StableOracleDAI.sol
+++ b/ussd-contracts/contracts/oracles/StableOracleDAI.sol
@@ -46,9 +46,10 @@ contract StableOracleDAI is IStableOracle {
         // chainlink price data is 8 decimals for WETH/USD, so multiply by 10 decimals to get 18 decimal fractional
         //(uint80 roundID, int256 price, uint256 startedAt, uint256 timeStamp, uint80 answeredInRound) = priceFeedDAIETH.latestRoundData();
         (, int256 price, , , ) = priceFeedDAIETH.latestRoundData();
+        uint256 priceETHDAI = 1e18 * 1e18 / uint256(price);

         return
             (wethPriceUSD * 1e18) /
-            ((DAIWethPrice + uint256(price) * 1e10) / 2);
+            ((DAIWethPrice + priceETHDAI) / 2);
     }
 }
```

Duplicate of #102

**Comment by securitygrid** [comment]
Escalate for 10 USDC
I think this is not a duplicate of #236. `priceFeedDAIETH.latestRoundData` gets **ether per DAI**. This report is the correct fix. Please review.

**Comment by ctf-sec** [comment]
Duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/909

**Comment by securitygrid** [comment]
This report merges #102 and #236.

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102 
Considering this a valid duplicate of #102

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/243/#issuecomment-1604518276): accepted
