### ISSUE TITLE
nobody2018 - The uniRouter used by USSD has no deadline detection, allowing outdated slippage and allow pending transaction to be unexpected executed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#249]
nobody2018

high

# The uniRouter used by USSD has no deadline detection, allowing outdated slippage and allow pending transaction to be unexpected executed

## Summary

The uniRouter used by USSD comes from [[this codebase](https://github.com/Uniswap/swap-router-contracts/blob/main/contracts/V3SwapRouter.sol)](https://github.com/Uniswap/swap-router-contracts/blob/main/contracts/V3SwapRouter.sol), and this version has no deadline detection, allowing outdated slippage and allow pending transaction to be unexpected executed.

## Vulnerability Detail

IV3SwapRouter.ExactInputParams is defined as follows:

```solidity
struct ExactInputParams {
        bytes path;
        address recipient;
        uint256 amountIn;
        uint256 amountOutMinimum;
    }
```

Let's look at this version of `exactInput`:

```solidity
function exactInput(ExactInputParams memory params) external payable override returns (uint256 amountOut) {
        ...
    }
```

it has no deadline check for the transaction when swapping.

## Impact

The pending transaction can be easily sandwiched. The longer the pending period, the greater the uncertainty of the price. Especially in the bull market, the gas is very high, and it is normal for a tx to be pending for a few days. Therefore, it is necessary to set a deadline.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSD.sol#L235

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSD.sol#L13

## Tool used

Manual Review

## Recommendation

USSD contract should use [[0xE592427A0AEce92De3Edee1F18E0157C05861564](https://etherscan.io/address/0xE592427A0AEce92De3Edee1F18E0157C05861564)](https://etherscan.io/address/0xE592427A0AEce92De3Edee1F18E0157C05861564) as uniRouter, and modify `ExactInputParams` in the `UniV3SwapInput` function. This version of SwapRouter comes from this [[codebase](https://github.com/Uniswap/v3-periphery/blob/main/contracts/SwapRouter.sol)](https://github.com/Uniswap/v3-periphery/blob/main/contracts/SwapRouter.sol). ExactInputParams structure is defined as follows:

```solidity
struct ExactInputParams {
        bytes path;
        address recipient;
        uint256 deadline;	//deadline added
        uint256 amountIn;
        uint256 amountOutMinimum;
    }
```

Duplicate of #673

**Comment by securitygrid** [comment]
Escalate for 10 USDC
I think this is not a duplicate of #673. 
Why deadline was commented? Because Routerv3 has two versions, one has a deadline parameter, and the other is not. The sponsor uses a version without deadline. This report describes the key to the problem.

**Comment by ctf-sec** [comment]
This is still a duplicate of #673, these two report talks about the same issue

In 673:

> [UniV3SwapInput()](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSD.sol#L227-L240) in USSD contract does not use the slippage parameter [amountOutMinimum](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSD.sol#L237) nor [deadline](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSD.sol#L235).

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #673 
Although this submission points out to additional information with the reason for the issue, the underlying issue and impact remains the same and can be considered duplicates.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [securitygrid](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/249/#issuecomment-1604687305): rejected
