### ISSUE TITLE
0xRobocop - USSD contract lacks slippage protection for minters

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#337]
0xRobocop

medium

# USSD contract lacks slippage protection for minters

## Summary

The `mintForToken()` function at the `USSD.sol` contract lacks slippage protection for minters. 

## Vulnerability Detail

When minting, users cannot specify a minimum amount of USSD tokens they are willing to accept for their collateral. If the oracles return incorrect prices or the transactions gets executed some blocks after the one the transaction got sent can cause loss of funds to the minter.

Scenarios where this can happen:

1.- Malfunction of oracles.- In case oracles return an incorrect price, for example a smaller valuation of the collateral, then users will receive less USSD, causing a direct loss, since the price was incorrect.

2.- Network Congestion.- Although EIP-1559 gives better gas-price predictability, it is still the case that during network-congestion some transactions get stuck as pending, until the gas-price decays. In other words, the transaction can get confirmed several blocks after the one in that was sent, and the price of the collateral could have decreased during this time.

## Impact

Loss of funds for the minter, since there is no `redeem` function to trade-back the USSD for the collateral, and the USSD / DAI uniswap pool is not guaranteed to have the sufficient liquidity to trade the USSD to DAI with a small slippage.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/USSD.sol#L151-L167

## Tool used

Manual Review

## Recommendation

Allow minters to specify the minimum amount of USSD tokens they are willing to accept in exchange for their collateral.

Duplicate of #97

**Comment by 0xRobocop** [comment]
Escalate for 10 USDC

This is not a duplicate of #673.

#673 Talks about that the contract does not have slippage protection when making trades in Uniswap, which I also reported in #334.

This issue talks about the lack of slippage protection for minters of USSD. For example, due to network congestion the collateral value of the minter might get lower between block `n` and block `n + k`, which will mint less USSD to the minter.

**Comment by ctf-sec** [comment]
duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/97

not a duplicate of #673

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #97
