### ISSUE TITLE
ast3ros - Price of DAI in USD should be obtained directly from Chainlink Oracle instead of calculated to increase accuracy

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#396]
ast3ros

medium

# Price of DAI in USD should be obtained directly from Chainlink Oracle instead of calculated to increase accuracy

## Summary

The StableOracleDAI calculates the price of DAI in USD by using the price from WETH Oracle, DAI/ETH priceFeed and DAI/ETH Uniswap Oracle. However, it can use the DAI/USD Chainlink Oracle directly to get a more accurate price.

## Vulnerability Detail

The price of DAI is calculated indirectly from multiple Oracles: WETH Oracle and the average of two DAI/ETH Oracles: TWAP DAI/ETH Uniswap Oracle with an average period of 600s and DAI/ETH Chainlink priceFeed. The average calculation and the use of TWAP Oracle reduce the accuracy of the price.

            return
            (wethPriceUSD * 1e18) / // (eth/usd) / (dai/weth + dai/weight)/2 => (weth/usd * dai/weth)
            ((DAIWethPrice + uint256(price) * 1e10) / 2);

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L50-L52

The protocol should use the DAI/USD Chainlink Oracle directly, as the price is aggregated from multiple sources and it sufficiently prevents price manipulation.

## Impact

The price of DAI in USD is not precise.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L50-L52

## Tool used

Manual Review

## Recommendation

The protocol should use the DAI/USD Chainlink Oracle directly to obtain the price of DAI.

**Comment by T1MOH593** [comment]
Escalate for 10 USDC

This is not a duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/909.
It tells about using 2 oracles: WETH/DAI and WETH/USD to calculate DAI/USD instead of using just DAI/USD. And #909 tells about completely different issue with oracles

**Comment by twicek** [comment]
Escalate for 10 USDC

This is a low/info. The choice of how the price is composed should be decided by the protocol's team. The fact that the protocol's team decided to used two different oracle feed for their DAI / USD price feed is a design choice. In other words, not using Chainlink as unique price feed is not an issue it's a design choice.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Not a duplicate of #909.
As pointed out in the above escalation this is a low issue as calculating the price of Dai from multiple sources is protocol choice.
