### ISSUE TITLE
nobody2018 - Malicious user transfers USSD or DAI to uniPool to affect the return value of USSDRebalancer.getSupplyProportion

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#405]
nobody2018

medium

# Malicious user transfers USSD or DAI to uniPool to affect the return value of USSDRebalancer.getSupplyProportion

## Summary

`getSupplyProportion` returns the balance of USSD and DAI held by `uniPool`. `USSDRebalancer.rebalance` uses the two balances to do the subtraction.

## Vulnerability Detail

The code for getSupplyProportion is as follows:

```solidity
function getSupplyProportion() public view returns (uint256, uint256) {
      uint256 vol1 = IERC20Upgradeable(uniPool.token0()).balanceOf(address(uniPool));
      uint256 vol2 = IERC20Upgradeable(uniPool.token1()).balanceOf(address(uniPool));
      if (uniPool.token0() == USSD) {
        return (vol1, vol2);
      }
      return (vol2, vol1);
    }
```

rebalance calls this function.

```solidity
function rebalance() override public {
      uint256 ownval = getOwnValuation();
->    (uint256 USSDamount, uint256 DAIamount) = getSupplyProportion();
      if (ownval < 1e6 - threshold) {
        // peg-down recovery
->      BuyUSSDSellCollateral((USSDamount - DAIamount / 1e12)/2);
      } else if (ownval > 1e6 + threshold) {
        // mint and buy collateral
        // never sell too much USSD for DAI so it 'overshoots' (becomes more in quantity than DAI on the pool)
        // otherwise could be arbitraged through mint/redeem
        // the execution difference due to fee should be taken into accounting too
        // take 1% safety margin (estimated as 2 x 0.5% fee)
->      IUSSD(USSD).mintRebalancer(((DAIamount / 1e12 - USSDamount)/2) * 99 / 100); // mint ourselves amount till balance recover
        SellUSSDBuyCollateral();
      }
    }
```

Bob can bring two impacts by transferring DAI or USSD to `uniPool`:

1.  Can make `BuyUSSDsellCollateral((USSDamount - DAIamount / 1e12)/2)` and `IUSSD(USSD).mintRebalancer(((DAIamount / 1e12 - USSDamount)/2) * 99 / 100)` revert due to subtraction overflow.
2.  Can control the value of param required by `BuyUSSDsellCollateral` and `mintRebalancer`, thereby affecting their logic. `SellUSSDBuyCollateral()` will also be affected, because the token minted by `mintRebalancer` is used by it.

## Impact

Vulnerability Detail has described 2 impacts.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L83-L90

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L97

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L104

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L164

## Tool used

Manual Review

## Recommendation

It is recommended not to use `erc20.balanceOf(pool)` as reliable data.

Duplicate of #808

**Comment by securitygrid** [comment]
Escalate for 10 USDC
This is a duplicate of #808.

**Comment by ctf-sec** [comment]
Duplicate of #808

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #808
