### ISSUE TITLE
0xRobocop - Incorrect accounting on the variable amountToBuyLeftUSD

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#520]
0xRobocop

medium

# Incorrect accounting on the variable amountToBuyLeftUSD

## Summary

Priority order of collateral to be sold is broken due to a lack of update on the `amountToBuyLeftUSD` variable.

## Vulnerability Detail

During a re-balancing in a peg-down recovery event, the function `BuyUSSDSellCollateral()` is used to sell collateral for DAI, then use this DAI to buy USSD from the DAI / USSD Uniswap pool, and the burn the USSD bought.

To achieve this, collateral is sold given a priority order and a variable `amountToBuyLeftUSD` is used to track how much is left to buy. This can bee [seen](https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/USSDRebalancer.sol#L119-L128) in the code:

```solidity
if (collateral[i].pathsell.length > 0) {
   uint256 amountBefore = IERC20Upgradeable(baseAsset).balanceOf(USSD);
   uint256 amountToSellUnits = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * ((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18) / 1e18;
   IUSSD(USSD).UniV3SwapInput(collateral[i].pathsell, amountToSellUnits);
   amountToBuyLeftUSD -= (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
   DAItosell += (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
} 
else {
   // no need to swap DAI
   DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
}
```

The case when the collateral is DAI (the else branch above) where no swap happens, the `amountToBuyLeftUSD` variable is not updated. 

## Impact

This will cause that collateral which is further on the priority order to get sold when it should not, breaking the assumption that DAI is a protection for the others more speculative collaterals. Quoting the whitepaper (section 5 paragraphs 4 and 5):

```solidity
/*
The collateral has selling priority (order), which is: 1. DAI, 2. WETH, 3. WBTC, 4. WBGL.
The goal of having an order of collateral liquidation is to have more volatile assets be further in the queue, allowing them to be accumulated and grow in value, while keeping DAI as near-line reserves and serve as a protection buffer from speculative manipulation.
*/
```

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/USSDRebalancer.sol#L119-L128

## Tool used

Manual Review

## Recommendation

Update the `amountToBuyLeftUSD` on the else branch

**Comment by 0xRobocop** [comment]
Escalate for 10 USDC

This is not a duplicate of #111.

#111 Talks about a possible underflow and hence a revert during a peg-down recovery scenario.

This issue has nothing to do with underflows / reverts. The issue points that the `amountToBuyLeftUSD` is not updated in the case of the `else` branch, which will cause the contract to sell more collateral when it should not. During peg-down recovery events the contract will try to buy USSD using DAI, if DAI balance is not enough then it will start selling the other collateral tokens:

```solidity
/*
The collateral has selling priority (order), which is: 1. DAI, 2. WETH, 3. WBTC, 4. WBGL.
The goal of having an order of collateral liquidation is to have more volatile assets be further in the queue, allowing them to be accumulated and grow in value, while keeping DAI as near-line reserves and serve as a protection buffer from speculative manipulation.
*/
```
But because the incorrect accounting it will sell collateral even though DAI balance can offset `amountToBuyLeftUSD`. For example:

DAI Balance = 1000
`amountToBuyLeftUSD` = 500.

The DAI balance can cover the amount of USSD needed to buy, but because `amountToBuyLeftUSD` is not updated it will sell other collaterals when it should not. The complete code is:

```solidity
for (uint256 i = 0; i < collateral.length; i++) {
        uint256 collateralval = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * 1e18 / (10**IERC20MetadataUpgradeable(collateral[i].token).decimals()) * collateral[i].oracle.getPriceUSD() / 1e18;
        if (collateralval > amountToBuyLeftUSD) {
          // sell a portion of collateral and exit
          if (collateral[i].pathsell.length > 0) {
            uint256 amountBefore = IERC20Upgradeable(baseAsset).balanceOf(USSD);
            uint256 amountToSellUnits = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * ((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18) / 1e18;
            IUSSD(USSD).UniV3SwapInput(collateral[i].pathsell, amountToSellUnits);
            amountToBuyLeftUSD -= (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
            DAItosell += (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
          } else {
            // no need to swap DAI
            DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
          }
```

It can be seen that in each instance of the for loop it compares the current collateral value to the `amountToBuyLeftUSD` variable. The first collateral in the array is DAI which does not need to be swapped, but it can be seen that the DAI branch (the `else` branch) does not update `amountToBuyLeftUSD`.

**Comment by hrishibhat** [comment]
@ctf-sec

**Comment by ctf-sec** [comment]
```solidity
  if (collateralval > amountToBuyLeftUSD) {
          // sell a portion of collateral and exit
          if (collateral[i].pathsell.length > 0) {
            uint256 amountBefore = IERC20Upgradeable(baseAsset).balanceOf(USSD);
            uint256 amountToSellUnits = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * ((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18) / 1e18;
            IUSSD(USSD).UniV3SwapInput(collateral[i].pathsell, amountToSellUnits);
            amountToBuyLeftUSD -= (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
            DAItosell += (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
          } else {
            // no need to swap DAI
            DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
          }
          break;
        }
```

if the sell path is not configurable and there is no swap happening, don't think we need to update amountToBuyLeftUSD

> This will cause that collateral which is further on the priority order to get sold when it should not, breaking the assumption that DAI is a protection for the others more speculative collaterals. Quoting the whitepaper (section 5 paragraphs 4 and 5):

if the higher priority swap path asset is not in configuration, I think selling the lower priority asset is the expected behavior

**Comment by hrishibhat** [comment]
@0xRobocop do you have a response to ctf_sec's comment?

**Comment by RobocopSR** [comment]
>if the sell path is not configurable and there is no swap happening, don't think we need to update amountToBuyLeftUSD

The USSD contract holds the collateral DAI, ETH, WBTC, BGL. During a peg-down scenario the contract will buy USSD in the DAI / USSD pool. Hence, the contract uses DAI to buy USSD, this can bee seen a little below in the same function:

```solidity
// buy USSD (sell DAI) to burn
      // never sell too much DAI so USSD 'overshoots' (becomes less in quantity than DAI on the pool)
      // otherwise could be arbitraged through mint/redeem
      // the remainder (should be small, due to oracle twap lag) to be left as DAI collateral
      // the execution difference due to fee should be taken into accounting too
      // take 1% safety margin (estimated as 2 x 0.5% fee)
      if (DAItosell > amountToBuy * 1e12 * 99 / 100) {
        DAItosell = amountToBuy * 1e12 * 99 / 100;
      }

      if (DAItosell > 0) {
        if (uniPool.token0() == USSD) {
            IUSSD(USSD).UniV3SwapInput(bytes.concat(abi.encodePacked(uniPool.token1(), hex"0001f4", uniPool.token0())), DAItosell);
        } else {
            IUSSD(USSD).UniV3SwapInput(bytes.concat(abi.encodePacked(uniPool.token0(), hex"0001f4", uniPool.token1())), DAItosell);
        }
      }

      IUSSD(USSD).burnRebalancer(IUSSD(USSD).balanceOf(USSD));
```

Thats why DAI (the first collateral to sell in the queue) is not swapped, because is already in the contract, the other collaterals are sold for DAI. 

> if the higher priority swap path asset is not in configuration, I think selling the lower priority asset is the expected behavior

I do understand your reasoning but that is not the intended design, because on the else branch "the no swap branch", it stills contributes to the `DAItosell` variable:

```solidity
else {
        // no need to swap DAI
        DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
}
```
So, it is not that DAI is not in the configuration because selling the lower priority asset is the expected behavior, is that DAI is already in the contract and that is why no sell path exists for it.

**Comment by hrishibhat** [comment]
@0xRobocop 
Why is there a need to update `amountToBuyLeftUSD`. There is a `break` right after selling DAI. 
There was enough DAI to be sold -> `DAItosell` is updated -> break out of the loop. 

```
  if (collateralval > amountToBuyLeftUSD) {
          // sell a portion of collateral and exit
          if (collateral[i].pathsell.length > 0) {
            uint256 amountBefore = IERC20Upgradeable(baseAsset).balanceOf(USSD);
            uint256 amountToSellUnits = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * ((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18) / 1e18;
            IUSSD(USSD).UniV3SwapInput(collateral[i].pathsell, amountToSellUnits);
            amountToBuyLeftUSD -= (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
            DAItosell += (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
          } else {
            // no need to swap DAI
            DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
          }
          break;
        }
``` 
Don't see an issue here.

**Comment by RobocopSR** [comment]
I'm incorrect, you are correct.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xRobocop](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/520/#issuecomment-1605635134): accepted
