### ISSUE TITLE
0xRobocop - Potentially incorrect accounting on the DAItosell variable

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#539]
0xRobocop

medium

# Potentially incorrect accounting on the DAItosell variable

## Summary

The contract assumes that the base asset will always be the first one on the `collaterals` array. In the case this assumption gets broken it will lead to an incorrect re-balancing during a peg-down recovery event.

## Vulnerability Detail

When selling the collateral on the `BuyUSSDSellCollateral()` function, if the collateral is the `baseAsset` then a swap is not needed, that is the else branch of the following code:

```solidity
if (collateral[i].pathsell.length > 0) {
   uint256 amountBefore = IERC20Upgradeable(baseAsset).balanceOf(USSD);
  uint256 amountToSellUnits = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * ((amountToBuyLeftUSD * 1e18 / collateralval) / 1e18) / 1e18;
   IUSSD(USSD).UniV3SwapInput(collateral[i].pathsell, amountToSellUnits);
   amountToBuyLeftUSD -= (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
   DAItosell += (IERC20Upgradeable(baseAsset).balanceOf(USSD) - amountBefore);
} 
else {        
  // no need to swap DAI
  DAItosell = IERC20Upgradeable(collateral[i].token).balanceOf(USSD) * amountToBuyLeftUSD / collateralval;
}
```

The code updates the `DAItosell` with a `=` instead of a `+=` which assumes that the base asset will always be the first one in the priority order of the collaterals when selling (which is not enforced on the code). In the case the base asset is not the first one in the array, then it will override the previous summation of `DAItosell`.

## Impact

An incorrect re-balancing during a peg-down recovery event because a wrong computation of the `DAItosell` variable.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/USSDRebalancer.sol#L127

## Tool used

Manual Review

## Recommendation

Change `=` to `+=`

**Comment by 0xRobocop** [comment]
Escalate for 10 USDC

This issue is not a duplicate of #111.

This issue talks about an incorrect accounting on the variable `DAItosell` when DAI is not the first collateral in the array. Basically it will override the current summation because `=` is used instead of a `+=`.

**Comment by ctf-sec** [comment]
> The contract assumes that the base asset will always be the first one on the collaterals array. In the case this assumption gets broken it will lead to an incorrect re-balancing during a peg-down recovery event.

This requires admin input issue:

https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/USSD.sol#L73

admin can call swapCollateralIndexes to avoid such issue

requires configuration error

valid low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Not a duplicate of #111 
Agree this reqiures admin input error.
The order of the array is important & is admin controlled and is expected to start with DAI. Considering this a low

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xRobocop](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/539/#issuecomment-1605587848): accepted
