### ISSUE TITLE
twicek - `DAIWethPrice` and Chainlink `price` have inversed quote and base token

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#555]
twicek

high

# `DAIWethPrice` and Chainlink `price` have inversed quote and base token

## Summary
`DAIWethPrice` and Chainlink `price` have inversed quote and base token but are summed up together.

## Vulnerability Detail
`DAIWethPrice` has for quote token DAI and for base token WETH:

[StableOracleDAI.sol#L36-L42](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L36-L42)
```solidity
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            pools, // DAI/WETH pool uni v3
            600 // period
        );
```
`price` is reported as a 18 decimals value with ETH as quote token and DAI as base token:
https://etherscan.io/address/0x773616e4d11a78f511299002da57a0a94577f1f4#readContract#F8

[StableOracleDAI.sol#L48](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L48)
```solidity
        (, int256 price, , , ) = priceFeedDAIETH.latestRoundData();
```
Therefore adding these two values doesn't make sense (I submitted the `price` decimal calculation problem in another report).

[StableOracleDAI.sol#L52](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L52)
```solidity
            ((DAIWethPrice + uint256(price) * 1e10) / 2);
```

## Impact
Wrong calculation will lead to wrong DAI / USD price reporting.

## Code Snippet
[StableOracleDAI.sol#L36-L42](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L36-L42)
[StableOracleDAI.sol#L48](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L48)
[StableOracleDAI.sol#L52](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L52)

## Tool used

Manual Review

## Recommendation
Take the inverse value of the Chainlink price before adding it to the Uniswap TWAP value to do the mean.

Duplicate of #102

**Comment by twicek** [comment]
Escalate for 10 USDC

The calculation done here:

[StableOracleDAI.sol#L50-L52](https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L50-L52)
```solidity
        return
            (wethPriceUSD * 1e18) /
            ((DAIWethPrice + uint256(price) * 1e10) / 2);
```
is composed of:

`wethPriceUSD`: how many USD are needed to buy a WETH -> ETH(base)/USD(quote)
`price`: how many ETH are needed to buy 1 DAI -> DAI(base)/ETH(quote)
`DAIWethPrice`: how many DAI are needed to buy 1 ETH -> ETH(base)/DAI(quote)

`price` is the [Chainlink price feed for DAI / ETH](https://etherscan.io/address/0x773616E4d11A78F511299002da57A0a94577F1f4#readContract#F10) which at the time of writing is 531887550554618. To understand this value we can use the equation:
1 ETH = 1878 DAI <=> 1 DAI = 5.325e-4 ETH
Therefore the Chainlink price report the price of DAI (base) in terms of ETH (quote) or in other words how many ETH are needed to buy one DAI.

`DAIWethPrice` is determined from `quoteSpecificPoolsWithTimePeriod` with as comments suggest WETH as base token and DAI as quote token. 

[StableOracleDAI.sol#L36-L42](https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L36-L42)
```solidity
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            pools, // DAI/WETH pool uni v3
            600 // period
        );
```

Without going further we can already notice that the two prices have inverted quote and base tokens as per comments. But let's look at `quoteSpecificPoolsWithTimePeriod`:

[UniswapV3StaticOracle.sol#L79-L87](https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/oracles/UniswapV3StaticOracle.sol#L79-L87)
```solidity
  function quoteSpecificPoolsWithTimePeriod(
    uint128 _baseAmount,
    address _baseToken,
    address _quoteToken,
    address[] calldata _pools,
    uint32 _period
  ) external view override returns (uint256 _quoteAmount) {
    return _quote(_baseAmount, _baseToken, _quoteToken, _pools, _period);
  }
```

Which call `_quote`:

[UniswapV3StaticOracle.sol#L160-L176](https://github.com/sherlock-audit/2023-05-USSD/blob/6d7a9fdfb1f1ed838632c25b6e1b01748d0bafda/ussd-contracts/contracts/oracles/UniswapV3StaticOracle.sol#L160-L176)
```solidity
  function _quote(
    uint128 _baseAmount,
    address _baseToken,
    address _quoteToken,
    address[] memory _pools,
    uint32 _period
  ) internal view returns (uint256 _quoteAmount) {
    require(_pools.length > 0, 'No defined pools');
    OracleLibrary.WeightedTickData[] memory _tickData = new OracleLibrary.WeightedTickData[](_pools.length);
    for (uint256 i; i < _pools.length; i++) {
      (_tickData[i].tick, _tickData[i].weight) = _period > 0
        ? OracleLibrary.consult(_pools[i], _period)
        : OracleLibrary.getBlockStartingTickAndLiquidity(_pools[i]);
    }
    int24 _weightedTick = _tickData.length == 1 ? _tickData[0].tick : OracleLibrary.getWeightedArithmeticMeanTick(_tickData);
    return OracleLibrary.getQuoteAtTick(_weightedTick, _baseAmount, _baseToken, _quoteToken);
  }
```

Which call `getQuoteAtTick` of the `OracleLibrary` contract in the [v3-periphery](https://github.com/Uniswap/v3-periphery/blob/main/contracts/libraries/OracleLibrary.sol) repos:

[OracleLibrary.sol#L43-L69](https://github.com/Uniswap/v3-periphery/blob/6cce88e63e176af1ddb6cc56e029110289622317/contracts/libraries/OracleLibrary.sol#L43-L69)
```solidity
    /// @notice Given a tick and a token amount, calculates the amount of token received in exchange
    /// @param tick Tick value used to calculate the quote
    /// @param baseAmount Amount of token to be converted
    /// @param baseToken Address of an ERC20 token contract used as the baseAmount denomination
    /// @param quoteToken Address of an ERC20 token contract used as the quoteAmount denomination
    /// @return quoteAmount Amount of quoteToken received for baseAmount of baseToken
    function getQuoteAtTick(
        int24 tick,
        uint128 baseAmount,
        address baseToken,
        address quoteToken
    ) internal pure returns (uint256 quoteAmount) {
        uint160 sqrtRatioX96 = TickMath.getSqrtRatioAtTick(tick);


        // Calculate quoteAmount with better precision if it doesn't overflow when multiplied by itself
        if (sqrtRatioX96 <= type(uint128).max) {
            uint256 ratioX192 = uint256(sqrtRatioX96) * sqrtRatioX96;
            quoteAmount = baseToken < quoteToken
                ? FullMath.mulDiv(ratioX192, baseAmount, 1 << 192)
                : FullMath.mulDiv(1 << 192, baseAmount, ratioX192);
        } else {
            uint256 ratioX128 = FullMath.mulDiv(sqrtRatioX96, sqrtRatioX96, 1 << 64);
            quoteAmount = baseToken < quoteToken
                ? FullMath.mulDiv(ratioX128, baseAmount, 1 << 128)
                : FullMath.mulDiv(1 << 128, baseAmount, ratioX128);
        }
    }
```

Which comments states that `quoteAmount Amount of quoteToken received for baseAmount of baseToken`. In this case quote amount being DAI and base amount being WETH, `getQuoteAtTick` will return a quote amount of DAI necessary to buy one WETH. So if 1878 DAI (quote) are necessary to buy the inputed 1 WETH (base) the function will return something like this: 1878000000000000000000.

To conclude:

`price`: how many ETH are needed to buy 1 DAI -> DAI(base)/ETH(quote)
`DAIWethPrice`: how many DAI are needed to buy 1 ETH -> ETH(base)/DAI(quote)

Therefore I think that my report is valid and should be high severity.

**Comment by ctf-sec** [comment]
I agree with the escalation

https://github.com/sherlock-audit/2023-05-USSD-judging/issues/491 https://github.com/sherlock-audit/2023-05-USSD-judging/issues/269 https://github.com/sherlock-audit/2023-05-USSD-judging/issues/102 https://github.com/sherlock-audit/2023-05-USSD-judging/issues/201 https://github.com/sherlock-audit/2023-05-USSD-judging/issues/795 https://github.com/sherlock-audit/2023-05-USSD-judging/issues/774.

are duplicate of this issue and this is separate valid medium issue

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [twicek](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/555/#issuecomment-1605840294): accepted
