### ISSUE TITLE
0xPkhatri - Incorrect Price Calculation in USSDRebalancer Due to Incorrect Decimal Consideration

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#574]
0xPkhatri

medium

# Incorrect Price Calculation in USSDRebalancer Due to Incorrect Decimal Consideration

## Summary

An incorrect price calculation has been discovered in USSDRebalancer#getOwnValuation. This issue arises from the improper consideration of decimal places.

## Vulnerability Detail

The DAI-USSD pool has not been deployed yet, thus for validating the getOwnValuation price, the DAI-USDC pool is used. In this scenario, token0 equals DAI with a value of sqrtPriceX96 being 79228721838302378450178. The decimal value for token0 (DAI) is 18, while token1 (USDC or USSD for our case) is 6.

The getOwnValuation function's 'else' statement calculates the price when token0 is DAI:

```solidity
else {
        price = uint(sqrtPriceX96)*(uint(sqrtPriceX96))*(1e18 /* 1e12 + 1e6 decimal representation */) >> (96 * 2);
        // flip the fraction
        price = (1e24 / price) / 1e12;
      }
     // price of USDC (USSD) in value of DAI 
    // output: price = 999985 ~= 10^6
```
Considering that DAI possesses 18 decimal points and both DAI and USSD are stable coins, the expected price output should be $price = 10^{18}$. However, an incorrect output of $price = 10^6$ is obtained.

The price calculation is incorrect. The detailed explanation on how to calculate the correct price described below:
reference from [uniswap-v3-math Reference](https://blog.uniswap.org/uniswap-v3-math-primer).

In uniswapV3 pool price is calculated as:

$$price = \frac{token1}{token0} = \left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2$$

Now consider case_1: 
```diff
uniPool.token0() == USSD
token0_decimal = 6   // USSD
token1_decimal = 18  // DAI
```

price can be calculated as:

$$price = \frac{DAI}{USSD} = \left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2$$

erc20 tokens have built in decimal values. USSD has 6 decimals and DAI has 18.
price of token0 in value of token1 :

$$adj\frac{DAI}{USSD} = \frac{\left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2}{\frac{10^{18}}{10^6}}$$

Convert to wei
price of token0 in value of token1 in lowest decimal :

$$
adj\frac{DAI}{USSD} = {\frac{\left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2}{\frac{10^{18}}{10^6}}}\cdot{10^{18}} = {\left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2}\cdot{10^{6}}
$$

Case_2:
```diff
uniPool.token0() != USSD
token0_decimal = 18   // DAI
token1_decimal = 6  // USSD
```

price can be calculated as:

$$price = \frac{USSD}{DAI} = \left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2$$

considering decimals.
price of token0 in value of token1 :

$$adj\frac{USSD}{DAI} = \frac{\left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2}{\frac{10^6}{10^{18}}}$$

Most exchanges quote the multiplicative inverse divide 1/price as

$$adj\frac{DAI}{USSD} = \frac{10^6}{{\left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2}\cdot{10^{18}}}$$

Convert to wei
price of token0 in value of token1 in lowest decimal :

$$
adj\frac{DAI}{USSD} = \frac{{10^6 \cdot 10^{18}}}{{\left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2 \cdot 10^{18}}} = \frac{{10^{24}}}{{\left(\frac{{\text{{sqrtPriceX96}}}}{{2^{96}}}\right)^2 \cdot 10^{18}}}
$$

## Impact

The incorrect price calculation might result in discrepancies, misinterpretation of the data.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L71-L80

## Tool used

Manual Review

## Recommendation
The getOwnValuation function could be restructured as follows to solve the issue:

```solidity
    function getOwnValuation() public view returns (uint256 price) {
      (uint160 sqrtPriceX96,,,,,,) =  uniPool.slot0();
      if(uniPool.token0() == USSD) {
        price = uint(sqrtPriceX96)*(uint(sqrtPriceX96))*(1e6) >> (96 * 2);
      } else {
        price = uint(sqrtPriceX96)*(uint(sqrtPriceX96))*(1e18 ) >> (96 * 2);
        // flip the fraction
        price = (1e24 / price);
      }
    }
```

Duplicate of #222

**Comment by 0xPkhatri** [comment]
This is duplicate of #222

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #222
