### ISSUE TITLE
0xPkhatri - Implications of Incorrect Precision Assumption on USSDRebalancer#rebalance Function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#621]
0xPkhatri

high

# Implications of Incorrect Precision Assumption on USSDRebalancer#rebalance Function

## Summary

An incorrect assumption was made during the development of the USSDRebalancer#rebalance function, specifically regarding the return value precision from the getOwnValuation function. This discrepancy arose from the assumption that the price would return a value with a 1e6 precision, when in reality it returns a 1e18 value. More details about this issue are provided below.

## Vulnerability Detail

The developer incorrectly assumed that the getOwnValuation function would return a price with a 1e6 precision while crafting the rebalance function. In reality, this function returns a value with a 1e18 precision because DAI, the stablecoin in question, has 18 decimal places. This can be seen in the getOwnValuation function [comment](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L70)

```diff
/// @dev get price estimation to DAI using pool address and uniswap price
```

For a correct logic, we could say that getOwnValuation will return the price of USSD in DAI value.

To illustrate this with the USDC-WETH price example:

USDC has 6 decimals and WETH has 18 decimals similar to our case now we can show price in two way:

(1)  price of WETH in value of USDC $(\frac{WETH}{USDC}) = 1825$
      # Convert to wei
      $$\text{price of WETH in value of USDC in lowest decimal  = }{1825} \cdot {10^6}$$

(2)  price of USDC in value of WETH $(\frac{USDC}{WETH}) = 0.0005479452$
      # Convert to wei
      $$\text{price of WETH in value of USDC in lowest decimal = }{0.0005479452} \cdot {10^{18}}{= 547945200000000}$$ 

When comparing USSD and DAI (both stablecoins), we find that the price:
 $$\text{price of USSD in value of DAI in lowest decimal  = }{1} \cdot {10^{18}}$$

Misconstruing this price as 1e6 can result in multiple issues such as incorrect threshold setting (which should be 10^16, not 10^4), and passing wrong values to the BuyUSSDSellCollateral and SellUSSDBuyCollateral functions, thereby causing a Denial of Service (DoS) within the system.

## Impact

Incorrect Threshold Setting: The precision assumption directly affects the setting of threshold values. Instead of being set to 10^16, the thresholds would be incorrectly set to 10^4 due to the 1e6 assumption.
Wrong values might be passed to the BuyUSSDSellCollateral and SellUSSDBuyCollateral functions due to the precision misunderstanding, potentially causing a Denial of Service in the system

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L92-L107

## Tool used

Manual Review

## Recommendation

It is advisable to rewrite the rebalance function while considering the price precision as 1e18.

Duplicate of #222

**Comment by 0xPkhatri** [comment]
Escalate for 10 USDC

This is duplicate of #909

**Comment by ctf-sec** [comment]
Validate duplicate of #909

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #222 
This issue is not a duplicate of #909. Considering this issue a duplicate of #222

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xPkhatri](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/621/#issuecomment-1604634882): accepted
