### ISSUE TITLE
Juntao - Incorrect calculation of DAI/USD price

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#641]
Juntao

high

# Incorrect calculation of DAI/USD price

## Summary
Incorrect calculation of DAI/USD price.

## Vulnerability Detail
In StableOracleDAI.sol, [getPriceUSD()](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L33C14-L53) is used to calculate DAI/USD price:
```solidity
    function getPriceUSD() external view override returns (uint256) {
        address[] memory pools = new address[](1);
        pools[0] = 0x60594a405d53811d3BC4766596EFD80fd545A270;
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            pools, // DAI/WETH pool uni v3
            600 // period
        );

        uint256 wethPriceUSD = ethOracle.getPriceUSD();

        // chainlink price data is 8 decimals for WETH/USD, so multiply by 10 decimals to get 18 decimal fractional
        //(uint80 roundID, int256 price, uint256 startedAt, uint256 timeStamp, uint80 answeredInRound) = priceFeedDAIETH.latestRoundData();
        (, int256 price, , , ) = priceFeedDAIETH.latestRoundData();

        return
            (wethPriceUSD * 1e18) /
            ((DAIWethPrice + uint256(price) * 1e10) / 2);
    }
```
Let's examine each variable used in the calculation:
```solidity
(wethPriceUSD * 1e18) / ((DAIWethPrice + uint256(price) * 1e10) / 2);
```

- [wethPriceUSD](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L44) is ETH/USD price in 18 decimals get from [StableOracleWETH](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleWETH.sol), which retrieves price data from Chainlink Price Feeds [0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419](https://etherscan.io/address/0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419):
```solidity
        uint256 wethPriceUSD = ethOracle.getPriceUSD();
``` 

- [DAIWethPrice](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L36-L42) is ETH/DAI quote price in 18 decimals get from Uniswap Pool:
```solidity
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            pools, // DAI/WETH pool uni v3
            600 // period
        );
```

- [price](https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L48) is DAI / ETH price in 18 decimals retrieved from Chainlink Price Feeds [0x773616E4d11A78F511299002da57A0a94577F1f4](https://etherscan.io/address/0x773616E4d11A78F511299002da57A0a94577F1f4):
```solidity
        (, int256 price, , , ) = priceFeedDAIETH.latestRoundData();
```

We can then see the way of calculation is essentially `ETH/USD / ((ETH/DAI + DAI/ETH) / 2)` which makes no sense.

## Impact
Incorrect DAI/USD price.

## Code Snippet
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L33C14-L53

## Tool used

Manual Review

## Recommendation
The correct way of calculation should be like (ETH/USD) * ((DAI/ETH + DAI/ETH) / 2) , please consider to modify as the followings:

1. get DAI/ETH price instead of ETH/DAI from Uniswap Pool:

```solidity
        // returns quoteAmount Amount of quoteToken received for baseAmount of baseToken
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 DAI
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (base token)
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (quote token)
            pools, // DAI/WETH pool uni v3
            600 // period
        );
```
2. Change the way of calculation:
```solidity
(wethPriceUSD) * ((DAIWethPrice + uint256(price)) / 2) / 1e18;
```

Duplicate of #102

**Comment by 0xcrunch** [comment]
Escalate for 10 USDC

This is a valid issue based on the report's description.
Let's assume:
```
wethPriceUSD = 2000e18 (IStableOracle, 18 decimals)
DAIWethPrice = 2000e18 (Uniswap, 18 decimals)
price = 0.0005e18 (Chainlink, ETH base, 18 decimals)
```
According to the way of calculation defined in the protocol:
`(wethPriceUSD * 1e18) / ((DAIWethPrice + uint256(price) * 1e10) / 2)`
We can get: 
`(2000e18 * 1e18) / ((2000e18 + 0.0005e18 * 1e10) / 2) = 0.000799e18`
and this is obviously wrong.

According to the way of calculation provided in recommendation:
`(ETH/USD) * ((DAI/ETH + DAI/ETH) / 2) => wethPriceUSD * ((1e36 / DAIWethPrice + uint256(price)) / 2) / 1e18;`
We can get:
`2000e18 * ((1e36 / 2000e18 + 0.0005e18) / 2) / 1e18 = 1e18`
and this is correct.

Please note by telling from the name, DAIWethPrice may be DAI/ETH, however, as WETH is passed as baseToken and baseAmount is 1e18, it actually returns the DAI amount per ETH, so in above case it's 2000e18:
```solidity
    function getPriceUSD() external view override returns (uint256) {
        address[] memory pools = new address[](1);
        pools[0] = 0x60594a405d53811d3BC4766596EFD80fd545A270; // @note Uniswap V3 pool to exchange between DAI and WETH
        // @note returns quoteAmount Amount of quoteToken received for baseAmount of baseToken
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            
            // @audit shoud be like:
            // 0x6B175474E89094C44Da98b954EedeAC495271d0F,
            // 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,

            pools, // DAI/WETH pool uni v3
            600 // period
        );
```
And you can find one implementation [here](https://etherscan.io/address/0xB210CE856631EeEB767eFa666EC7C1C57738d438#code) for reference.

Also there are some misconfigurations in this protocol, those should be consider as different issues from this one.

**Comment by juntzhan** [comment]
Escalate for 10 USDC

This is a valid issue based on the report's description.
Let's assume:
```
wethPriceUSD = 2000e18 (IStableOracle, 18 decimals)
DAIWethPrice = 2000e18 (Uniswap, 18 decimals)
price = 0.0005e18 (Chainlink, ETH base, 18 decimals)
```
According to the way of calculation defined in the protocol:
`(wethPriceUSD * 1e18) / ((DAIWethPrice + uint256(price) * 1e10) / 2)`
We can get: 
`(2000e18 * 1e18) / ((2000e18 + 0.0005e18 * 1e10) / 2) = 0.000799e18`
and this is obviously wrong.

According to the way of calculation provided in recommendation:
`(ETH/USD) * ((DAI/ETH + DAI/ETH) / 2) => wethPriceUSD * ((1e36 / DAIWethPrice + uint256(price)) / 2) / 1e18;`
We can get:
`2000e18 * ((1e36 / 2000e18 + 0.0005e18) / 2) / 1e18 = 1e18`
and this is correct.

Please note by telling from the name, DAIWethPrice may be DAI/ETH, however, as WETH is passed as baseToken and baseAmount is 1e18, it actually returns the DAI amount per ETH, so in above case it's 2000e18:
```solidity
    function getPriceUSD() external view override returns (uint256) {
        address[] memory pools = new address[](1);
        pools[0] = 0x60594a405d53811d3BC4766596EFD80fd545A270; // @note Uniswap V3 pool to exchange between DAI and WETH
        // @note returns quoteAmount Amount of quoteToken received for baseAmount of baseToken
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            
            // @audit shoud be like:
            // 0x6B175474E89094C44Da98b954EedeAC495271d0F,
            // 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2,

            pools, // DAI/WETH pool uni v3
            600 // period
        );
```
And you can find one implementation [here](https://etherscan.io/address/0xB210CE856631EeEB767eFa666EC7C1C57738d438#code) for reference.

Also there are some misconfigurations in this protocol, those should be consider as different issues from this one.

**Comment by hrishibhat** [comment]
@ctf-sec this should be a duplicate of #102 correct?

**Comment by ctf-sec** [comment]
I agree

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [juntzhan](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/641/#issuecomment-1605239937): accepted
