### ISSUE TITLE
sashik_eth - Wrong calculation in WBTC oracle

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#675]
sashik_eth

medium

# Wrong calculation in WBTC oracle

## Summary

Wrong calculation in WBTC oracle.

## Vulnerability Detail

WBTC oracle would use BTC/USD Chainlink priceFeef. However, while WBTC is pegged to BTC price it's not always the same. So for correct evaluation of WBTC collateral amount should be used ratio of WBTC/BTC and BTC/USD chainlink priceFeeds.

## Impact

The price of WBTC would be wrongly evaluated as the price of BTC, which is not always the same. Resulting in incorrect collateral evaluation.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleWBTC.sol#L23

## Tool used

Manual Review

## Recommendation

Consider using the ratio between WBTC/BTC and BTC/USD chainlink priceFeeds for the correct evaluation of WBTC price.

Duplicate of #310

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
Issue wrongly marked as a duplicate of #817 
This issue is connected not with the address of oracle but with the way the WBTC price is calculated. 
Chainlink provides a separate price feed for WBTC/BTC price, but not for WBTC/USD:
https://data.chain.link/ethereum/mainnet/crypto-other/wbtc-btc
So the price of WBTC/USD should be calculated based on WBTC/BTC and BTC/USD price feeds.

**Comment by cryptostaker2** [comment]
Want to echo that issues #202, #124, #823, #789, #534, #581, #646, #656, #445, #380, #310 also talks about the same problem and is incorrectly classified as "wrong address"

**Comment by ctf-sec** [comment]
I think https://github.com/sherlock-audit/2023-05-USSD-judging/issues/202, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/124, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/823, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/789, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/534, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/581, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/646, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/656, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/445, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/380, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/310, https://github.com/sherlock-audit/2023-05-USSD-judging/issues/74 can be a duplicate of this issue #675 and a new valid medium can be added

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #310

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/675/#issuecomment-1605901066): accepted
