### ISSUE TITLE
sashik_eth - Incorrect order of calculation in DAI oracle

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#684]
sashik_eth

high

# Incorrect order of calculation in DAI oracle

## Summary

Incorrect order of calculation in DAI oracle.

## Vulnerability Detail

DAI oracle uses multiple price sources to evaluate the correct price of DAI. It uses ETH price oracle, DAI/WETH UNI pool, and DAI/ETH Chainlink priceFeed:
```solidity
    function getPriceUSD() external view override returns (uint256) {
        address[] memory pools = new address[](1);
        pools[0] = 0x60594a405d53811d3BC4766596EFD80fd545A270;
        uint256 DAIWethPrice = DAIEthOracle.quoteSpecificPoolsWithTimePeriod(
            1000000000000000000, // 1 Eth
            0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2, // WETH (base token)
            0x6B175474E89094C44Da98b954EedeAC495271d0F, // DAI (quote token)
            pools, // DAI/WETH pool uni v3
            600 // period
        );

        uint256 wethPriceUSD = ethOracle.getPriceUSD();

        // chainlink price data is 8 decimals for WETH/USD, so multiply by 10 decimals to get 18 decimal fractional
        //(uint80 roundID, int256 price, uint256 startedAt, uint256 timeStamp, uint80 answeredInRound) = priceFeedDAIETH.latestRoundData();
        (, int256 price, , , ) = priceFeedDAIETH.latestRoundData();

        return
            (wethPriceUSD * 1e18) /
            ((DAIWethPrice + uint256(price) * 1e10) / 2); // @audit high: wrong calculation
    }
```

However in the `return` statement of a function above we could see incorrect order of prices. While `DAIWethPrice` is equivalent to WETH/DAI ratio (due to params order in oracle call), the `price` value is equivalent to DAI/ETH ratio (due to Chainlunk oracle). This would result in the incorrect value of the DAI price.

## Impact

Incorrect evaluation of DAI price results in wrong calculation during minting and rebalancing.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L52

## Tool used

Manual Review

## Recommendation

Consider updating the calculation in the `return` statement of a DAI oracle `getPriceUSD` function.

Duplicate of #102

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
This is a valid issue since the current implementation leads to the wrong calculation of price.
Denominator in the return statement use `DAIWethPrice` which is WETH/DAI ratio (~1800) and  `uint256(price)` from Chainlink price feed which is DAI/WETH ratio (~0.00052).

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/684/#issuecomment-1605903405): accepted
