### ISSUE TITLE
shaka - WBGL and WBTC can be paused

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#69]
shaka

high

# WBGL and WBTC can be paused

## Summary

WBGL and WBTC can be paused.

## Vulnerability Detail

In the README file it is stated the following

> `we don't expect that this contract activity could be paused from outside.`

Given that the WBGL and WBTC can be paused, this would not make possible to mint them or used them to rebalance the collateral/USSD in case of a depeg event.

## Impact

If WBGL or WBTC are paused, the stability mechanisms of the protocol will stop working.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSD.sol#L75

## Tool used

Manual Review

## Recommendation

Avoid using as collateral tokens that can be paused.

**Comment by shaka0x** [comment]
Escalate for 10 USDC

In the Q&A section of the README we can read:
> **Q: In case of external protocol integrations, are the risks of external contracts pausing or executing an emergency withdrawal acceptable? If not, Watsons will submit issues related to these situations that can harm your protocol's functionality.**
No, we don't expect that this contract activity could be paused from outside.

This issue gives a clear example of integrations with external contracts that have the ability of pausing and harming the protocol functionality.

**Comment by ctf-sec** [comment]
the WBTC can be paused that is true.

https://etherscan.io/token/0x2260fac5e5542a773aa44fbcfedf7c193bc2c599#code#L486

emm valid issue, severity is not high, on the verge of medium / low, 

I think the severity is low

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Agree with the Lead Judge that this issue can be considered low.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low because of the unlikely event of pause and depeg happening the collateral can be removed to allow relabance to function normally.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [shaka0x](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/69/#issuecomment-1605619196): rejected
