### ISSUE TITLE
0xPkhatri - Incorrect Calculation return in StableOracleDAI#getPriceUSD Function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#758]
0xPkhatri

high

# Incorrect Calculation return in StableOracleDAI#getPriceUSD Function

## Summary

The StableOracleDAI#getPriceUSD function is incorrectly computing the DAI/USD price due to improper handling of exchange rates and decimal precision. A detailed given below.

## Vulnerability Detail

In the StableOracleDAI#getPriceUSD function, three prices are used: wethPriceUSD, DAIWethPrice, and priceFeedDAIETH price to calculate the DAI/USD rate. However, there are two issues in the computation of the DAI/USD price:

1. while taking average we need to consider that DAIWethPriceis giving $\frac{WETH}{DAI}$ rate but chainlink priceFeedDAIETH price giving $\frac{DAI}{WETH}$  rate so while calculating average we calculate wrong rate.

```solidity
        return
            (wethPriceUSD * 1e18) /
            ((DAIWethPrice + uint256(price) * 1e10) / 2);
```

2. The priceFeedDAIETH returns an 18-decimal rate, not an 8-decimal rate. This can be verified on [Etherscan](https://etherscan.io/address/0x773616E4d11A78F511299002da57A0a94577F1f4#readContract#F3). Thus, when calculating the average, it's incorrect to multiply the price by $10^{10}$.

```solidity
        // chainlink price data is 8 decimals for WETH/USD, so multiply by 10 decimals to get 18 decimal fractional

        (, int256 price, , , ) = priceFeedDAIETH.latestRoundData();
```

## Impact

The incorrect DAI price calculation can result in a wrong price return from getPriceUSD function.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/oracles/StableOracleDAI.sol#L46-L53

## Tool used

Manual Review

## Recommendation

It's recommended to revise the calculation method used in the getPriceUSD function to correctly account for the different exchange rates and decimal precision.

Duplicate of #102

**Comment by 0xPkhatri** [comment]
Escalate for 10 USDC

This is not a duplicate of #236 
this is duplicate of #795

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xPkhatri](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/758/#issuecomment-1604649041): accepted
