### ISSUE TITLE
sashik_eth - USSD is not overcollateralized during minting

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#771]
sashik_eth

high

# USSD is not overcollateralized during minting

## Summary

USSD is not overcollateralized during minting.

## Vulnerability Detail

Users are able to mint new USSD tokens by providing an equivalent ($1 asset to 1 USSD) amount of collateral tokens:
```solidity
    function mintForToken( 
        address token,
        uint256 tokenAmount,
        address to
    ) public returns (uint256 stableCoinAmount) {
        require(hasCollateralMint(token), "unsupported token");

        IERC20Upgradeable(token).safeTransferFrom(
            msg.sender,
            address(this),
            tokenAmount
        );
        stableCoinAmount = calculateMint(token, tokenAmount);
        _mint(to, stableCoinAmount);

        emit Mint(msg.sender, to, token, tokenAmount, stableCoinAmount);
    }

    /// @dev Return how much STABLECOIN does user receive for AMOUNT of asset
    function calculateMint(address _token, uint256 _amount) public view returns (uint256 stableCoinAmount) { 
        uint256 assetPrice = collateral[getCollateralIndex(_token)].oracle.getPriceUSD();
        return (((assetPrice * _amount) / 1e18) * (10 ** decimals())) / (10 ** IERC20MetadataUpgradeable(_token).decimals());
    }
```

However, protocol documentation and rebalancing logic are based on the assumption that USSD should be overcollateralized (have more collateral assets than minted tokens).

## Impact

USSD tokens mints not overcollateralized while should be. Breaking one of the main protocol assumptions.

## Code Snippet

https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSD.sol#L170

## Tool used

Manual Review

## Recommendation

Consider updating the minting function in a way where the minter provides the appropriate amount of collateral so USSD become overcollateralized.

**Comment by sashik-eth** [comment]
Escalate for 10 USDC
This issue should be a valid medium in case #836 is considered as such

**Comment by ctf-sec** [comment]
duplicate of #836

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Lead Watson comment:
> This is not a dup of #836 and it's invalid: the issues is build upon a wrong understanding of the design, the minting of USSD is not always overcollateralized, but it supposed to build the ratio of overcollateralization over time. It's part of the design that the first stage is not overcollateralized.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [sashik-eth](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/771/#issuecomment-1606071712): rejected
