### ISSUE TITLE
Bahurum - `price` is DAI/ETH instead of ETH/DAI in `StableOracleDAI.getPriceUSD()`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#795]
Bahurum

high

# `price` is DAI/ETH instead of ETH/DAI in `StableOracleDAI.getPriceUSD()`

## Summary
In `StableOracleDAI`, `price` is supposed to be the price of ETH in DAI, but is the price of DAI in ETH instead.

## Vulnerability Detail

`StableOracleDAI.getPriceUSD()` takes the average of the UniV3 WETH-DAI TWAP price and the DAI/ETH Chainlink oracle price.

`DAIWethPrice` is the amount of DAI corresponding to 1 ETH, while `price` is the amount of ETH in 1 DAI. The average in:
```solidity
        return
            (wethPriceUSD * 1e18) /
            ((DAIWethPrice + uint256(price) * 1e10) / 2);
```
is incorrect as `price` is much smaller than it should be. 

When an user calls `USSD.mintForToken()` using DAI, he will obtain an incorrect amount of USSD.

## Impact
DAI price used is incorrect, causing amounts minted with DAI to be incorrect.

## Code Snippet
https://github.com/USSDofficial/ussd-contracts/blob/f44c726371f3152634bcf0a3e630802e39dec49c/contracts/oracles/StableOracleDAI.sol#L33-L53

## Tool used

Manual Review

## Recommendation
Compute the ETH/DAI price from the DAI/ETH chainlink feed.

```diff
        ...
        (, int256 price, , , ) = priceFeedDAIETH.latestRoundData();
+       price = 1e36 / uint256(price)
        ...
```

Duplicate of #102

**Comment by T1MOH593** [comment]
Escalate for 10 USDC

This is not a duplicate of https://github.com/sherlock-audit/2023-05-USSD-judging/issues/909.
It tells about using DAI/ETH instead of ETH/DAI on Chainlink. And https://github.com/sherlock-audit/2023-05-USSD-judging/issues/909 tells about completely different issue with oracles

**Comment by ctf-sec** [comment]
This is still a duplicate of #909 

In this issue:

> It tells about using DAI/ETH instead of ETH/DAI on Chainlink

In #909 WBTC should use WBTC/ETH ETH/DAI

**Comment by hrishibhat** [comment]
Result:
High
Duplicate of #102

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [T1MOH593](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/795/#issuecomment-1604543666): accepted
