### ISSUE TITLE
neumo - SellUSSDBuyCollateral should not sell the whole USSD contract balance fro DAI

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-05-USSD-judging#897]
neumo

high

# SellUSSDBuyCollateral should not sell the whole USSD contract balance fro DAI

## Summary
Function `SellUSSDBuyCollateral` is called in contract `USSDRebalancer` to control the peg of USSD to DAI. But it sells the whole balance of USSD existing in the `USSD` contract, instead of just the amount minted. 

## Vulnerability Detail
As explained in the summary, this fact opens up a price manipulation attack where an attacker can send an arbitrary amount of USSD to the USSD contract, knowing that a call to rebalance will sell too much USSD for DAI.

As we can see in the first lines of the function:
```solidity
function SellUSSDBuyCollateral() internal {
  uint256 amount = IUSSD(USSD).balanceOf(USSD);
  // sell for DAI then swap by DAI routes
  uint256 daibought = 0;
  if (uniPool.token0() == USSD) {
	daibought = IERC20Upgradeable(baseAsset).balanceOf(USSD);
	IUSSD(USSD).UniV3SwapInput(bytes.concat(abi.encodePacked(uniPool.token0(), hex"0001f4", uniPool.token1())), amount);
	daibought = IERC20Upgradeable(baseAsset).balanceOf(USSD) - daibought; // would revert if not bought
  } else {
	daibought = IERC20Upgradeable(baseAsset).balanceOf(USSD);
	IUSSD(USSD).UniV3SwapInput(bytes.concat(abi.encodePacked(uniPool.token1(), hex"0001f4", uniPool.token0())), amount);
	daibought = IERC20Upgradeable(baseAsset).balanceOf(USSD) - daibought; // would revert if not bought
  }
...
```

The amount of USSD that is swapped in Uniswap for DAI is the whole balance of the contract, not the amount minted in the call to the `rebalance` function:
```solidity
...
IUSSD(USSD).mintRebalancer(((DAIamount / 1e12 - USSDamount)/2) * 99 / 100); // mint ourselves amount till balance recover
SellUSSDBuyCollateral();
...
```

## Impact
High.

## Code Snippet
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L104-L105
https://github.com/sherlock-audit/2023-05-USSD/blob/main/ussd-contracts/contracts/USSDRebalancer.sol#L164

## Tool used
Manual review.

## Recommendation
Make function `SellUSSDBuyCollateral` receive an `amount` parameter, to just sell the amount minted, not the whole balance.

**Comment by hrishibhat** [comment]
@ctf-sec

**Comment by ctf-sec** [comment]
> This bug would allow anyone to donate an arbitrary amount of ÙSSD to the USSD contract, making the amount of USSD overshoot if compared to the amount of DAI in the UNI pool.

Attacker would need to acquire the USSD and lose fund and some arbitrager can bring the USSD price back in the UNI pool

**Comment by neumoxx** [comment]
The attacker maybe would have no profit, or maybe he could arbitrage himself after the donation and make some profit, I really don't know. What is clear to me is that the amount that should be swapped in the pool is exactly the amount minted in the call to rebalance, and the fact that anybody can alter the proportion of USSD/DAI of the pool, should be at least a medium severity.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue low based on:
https://github.com/sherlock-audit/2023-05-USSD-judging/issues/902#issuecomment-1636704253

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [neumoxx](https://github.com/sherlock-audit/2023-05-USSD-judging/issues/897/#issuecomment-1605439002): rejected
